language: node_js
node_js:
  - "10"

before_deploy:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - cp .npmrc-publish .npmrc

deploy:
  provider: script
  script: npx lerna publish -y from-git
  skip_cleanup: true
  on:
    tags: true
    branch: master
